<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_themehelper = $this->helper('Crealevant\Relevant\Helper\Data');
$_hultenHelper = $this->helper('Crealevant\Hultens\Helper\Data');
$imageHelper = $block->getImageHelper();
$priceHelper = $block->getPricingHelper();
$typeInstance = $block->getBundleProductType()
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $imgBlock = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <div class="product-item-container">
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                            <?php
                            $qty = $_themehelper->getStockQty($_product);
                            echo '<div class="flag-container">';
                            echo $_themehelper->getFlags($_product, 'no');
                            echo '</div>';
                            ?>
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php
                            $product = $block->getProductBySku($_product->getSku());

                            $images = $product->getMediaGalleryImages();
                            $imgCNT = 1;
                            $imgurl2 = "";

                            foreach ($images as $child) {
                                if ($imgCNT == 1) {
                                    $imgurl1 = $child->getUrl();
                                } elseif ($imgCNT == 2) {
                                    $imgurl2 = $imageHelper->init($_product, 'product_page_image_large')->keepAspectRatio(true)->keepFrame(true)->setImageFile($child->getFile())->resize($productImage->getWidth(), $productImage->getHeight())->getUrl();
                                } else {
                                    break;
                                }
                                $imgCNT++;
                            }
                            $imageUrl = $imageHelper->init($_product, 'product_page_image_large')->keepAspectRatio(true)->keepFrame(true)->resize($productImage->getWidth(),$productImage->getHeight())->getUrl(); ?>

                            <?php // Product Image ?>
                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?= $productImage->toHtml() ?>
                                <input class="hide switcher-img <?php echo ($imgurl2) ? "is-image" : "no-image" ?>" data-value="<?php echo ($imgurl2) ? $imgurl2 : $imageUrl; ?>"/>
                            </a>
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php
                                $isSpecial = false;
                                $isAppyRules = false;
                                $price = '';
                                $_originalPrice = '';
                                $newPrice = '';
                                $_specialPriceSelection = '';
                                $_regularPriceSelection = '';
                                $selections = $typeInstance->getSelectionsCollection($typeInstance->getOptionsIds($_product), $_product); ?>

                                <?php if($_product->getTypeId() == 'bundle'): ?>
                                    <?php $originalPrice = 0;
                                    $_oldPrice = 0;
                                    $_oldPriceRule = 0;
                                    $_specialSelectionPrice = "";
                                    $productPriceRule = false;
                                    $_specialPrice = 0;
                                    $_specialPriceRule = 0;?>
                                    <?php foreach ($selections as $selection): ?>
                                        <?php if ($selection->getIsDefault() == '1'): ?>
                                            <?php $newRegularPrice = $selection->getPriceInfo()->getPrice('regular_price')->getValue();
                                            $newSpecialPrice = $selection->getPriceInfo()->getPrice('final_price')->getValue();
                                            $_specialSelectionPrice = $selection->getSpecialPrice();
                                            $qty = $selection->getSelectionQty();
                                            $selectionProduct = $_hultenHelper->getProduct($selection->getProductId());
                                            $productPriceRule = $_hultenHelper->getPrice($selectionProduct, $newRegularPrice);
                                            //Setup current Date and Get From/To Date ( Bundle/SpecialPrice )
                                            $todaysDate =  date("Y-m-d");
                                            $FromDate = $selection->getSpecialFromDate();
                                            $ToDate = $selection->getSpecialToDate();
                                            $originalPrice += $newRegularPrice * $qty;?>

                                            <?php if ($newSpecialPrice): ?>
                                                <?php $_oldPrice += $newRegularPrice * $qty; ?>
                                                <?php $_specialPrice += $newSpecialPrice * $qty; ?>
                                            <?php endif; ?>

                                            <?php if($productPriceRule): ?>
                                                <?php $_oldPriceRule += $newRegularPrice * $qty; ?>
                                                <?php $_specialPriceRule += $productPriceRule * $qty; ?>
                                                <?php $isAppyRules = true; ?>
                                            <?php endif; ?>

                                            <?php if($_specialSelectionPrice): ?>
                                                <?php if(($todaysDate > $FromDate) && ($todaysDate < $ToDate)): ?>
                                                    <?php $isSpecial = true; ?>
                                                <?php elseif($todaysDate > $FromDate && empty($ToDate)): ?>
                                                    <?php $isSpecial = true; ?>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>

                                    <?php if($isAppyRules): ?>
                                        <div class="price-box">
                                    <span class="special-price">
                                        <span class="price-container">
                                            <span class="price-wrapper">
                                                <span class="price"> <?= $priceHelper->currency($_specialPriceRule, true, false);  ?> </span>
                                            </span>
                                        </span>
                                    </span>
                                            <span class="old-price">
                                        <span class="price-container">
                                            <span class="price-wrapper">
                                                <span class="price"> <?= $priceHelper->currency($_oldPriceRule, true, false);  ?> </span>
                                            </span>
                                        </span>
                                    </span>
                                        </div>
                                        <?php // If selection product has special price ?>
                                    <?php elseif($isSpecial): ?>
                                        <div class="price-box">
                                    <span class="special-price">
                                        <span class="price-container">
                                            <span class="price-wrapper">
                                                <span class="price"> <?= $priceHelper->currency($_specialPrice, true, false);  ?> </span>
                                            </span>
                                        </span>
                                    </span>
                                            <span class="old-price">
                                        <span class="price-container">
                                            <span class="price-wrapper">
                                                <span class="price"> <?= $priceHelper->currency($_oldPrice, true, false);  ?> </span>
                                            </span>
                                        </span>
                                    </span>
                                        </div>
                                    <?php else: ?>
                                        <div class="price-box">
                                    <span class="price-container">
                                        <span class="price-wrapper">
                                            <span class="price"> <?= $priceHelper->currency($originalPrice, true, false);  ?> </span>
                                        </span>
                                    </span>
                                        </div>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <?php $customisableOptions = $block->getCustomizableOptions($_product); // Get Custom Options From Simple
                                    // Product ?>
                                    <?php $customOptionTotalPrice = 0; ?>
                                    <?php $showCustomOptionPrice = false; ?>
                                    <?php $isAppyRules = false; ?>
                                    <?php $isSpecial = false; ?>

                                    <?php  // Data - Get Product prices. ?>
                                    <?php $catalogPriceRule = $_product->getPriceInfo()->getPrice('catalog_rule_price')->getValue(); ?>
                                    <?php $normalPrice = $priceHelper->currency($_product->getPrice(), false, false); ?>
                                    <?php $finalPrice = $priceHelper->currency($_product->getPriceInfo()->getPrice('final_price')->getValue(), false, false); ?>
                                    <?php $_specialPrice = $priceHelper->currency($_product->getSpecialPrice(), false, false); ?>

                                    <?php  // Data - Get Product Special Dates. ?>
                                    <?php $todaysDate =  date("Y-m-d"); ?>
                                    <?php $FromDate = $_product->getSpecialFromDate(); ?>
                                    <?php $ToDate = $_product->getSpecialToDate(); ?>

                                    <?php foreach ($customisableOptions as $option):
                                         $values = $option->getValues();
                                         //check if option has values (Option can have values only if option type is checkbox, radio, multiselect or drop-down)
                                        if ($values):
                                            foreach ($values as $value):
                                                //do whatever you want will value data "Is Default"
                                                $optionIsDefault = $value->getData('is_default');
                                                // Data - Get Product id from option sku.
                                                $productBySku = $block->getProductBySku($value->getSku());
                                                if ($productBySku):
                                                    if ($optionIsDefault) :
                                                        $showCustomOptionPrice = true;
                                                        $customOptionPrice = $productBySku->getPrice();
                                                        $customOptionTotalPrice += $customOptionPrice;
                                                    endif;

                                                    $normalPriceWithOptions = $customOptionTotalPrice + $normalPrice;
                                                    $finalPriceWithOptions = $customOptionTotalPrice + $finalPrice;
                                                endif;
                                            endforeach;
                                        endif;
                                    endforeach;

                                    if ($_specialPrice):
                                        if (($todaysDate > $FromDate) && ($todaysDate < $ToDate)):
                                            $isSpecial = true;
                                        elseif ($todaysDate > $FromDate && empty($ToDate)):
                                            $isSpecial = true;
                                        endif;
                                    endif; ?>

                                    <?php if($catalogPriceRule): ?>
                                        <?php $isAppyRules = true; ?>
                                    <?php endif; ?>

                                    <?php // If product is has custom option is set "isDefault(Admin Product View)" ?>
                                    <?php if($showCustomOptionPrice): ?>
                                        <?php if($isAppyRules): ?>
                                            <div class="price-box">
                                                <span class="special-price">
                                                    <span class="price-container">
                                                        <span class="price-wrapper">
                                                            <span class="price"> <?= $priceHelper->currency($finalPriceWithOptions, true, false);  ?> </span>
                                                        </span>
                                                    </span>
                                                </span>
                                                <span class="old-price">
                                                    <span class="price-container">
                                                        <span class="price-wrapper">
                                                            <span class="price"> <?= $priceHelper->currency($normalPriceWithOptions, true, false);  ?> </span>
                                                        </span>
                                                    </span>
                                                </span>
                                            </div>
                                        <?php elseif($isSpecial): ?>
                                            <div class="price-box">
                                                <span class="special-price">
                                                    <span class="price-container">
                                                        <span class="price-wrapper">
                                                            <span class="price"> <?= $priceHelper->currency($finalPriceWithOptions, true, false);  ?> </span>
                                                        </span>
                                                    </span>
                                                </span>
                                                <span class="old-price">
                                                    <span class="price-container">
                                                        <span class="price-wrapper">
                                                            <span class="price"> <?= $priceHelper->currency($normalPriceWithOptions, true, false);  ?> </span>
                                                        </span>
                                                    </span>
                                                </span>
                                            </div>
                                        <?php else: ?>
                                            <div class="price-box">
                                                <span class="price-container">
                                                    <span class="price-wrapper">
                                                        <span class="price"> <?= $priceHelper->currency($normalPriceWithOptions, true, false);  ?> </span>
                                                    </span>
                                                </span>
                                            </div>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?= $block->getProductPrice($_product); ?>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?= $block->getProductDetailsHtml($_product) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription):?>
                                        <div class="product description product-item-description">
                                            <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                               class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                </div>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>