<?php
$_product = $block->getProduct();

//Values
$green = $_product->getData('inventory_green_status_min'); //returns null
$red = $_product->getData('inventory_red_status_max'); // Returns string(2) "10"

//Labels
$greenLabel = $_product->getAttributeText('inventory_green_status_text'); // Returns bool(false)
$redLabel = $_product->getAttributeText('inventory_red_status_text'); // Returns bool(false)
$yellowLabel = $_product->getAttributeText('inventory_yellow_status_text'); // Returns bool(false)

//Stock
$greenStat = intval($_product->getData('inventory_green_status_min')); // Returns int(0)
$redStat = intval($_product->getData('inventory_red_status_max')); // Returns int(10)
$yellowTxt = $_product->getResource()->getAttribute('inventory_yellow_status_text')->getFrontend()->getValue($_product); // Returns: string(46) "Fåtal kvar i lager. Leverans 2-7 arbetsdagar."
$redTxt = $_product->getResource()->getAttribute('inventory_red_status_text')->getFrontend()->getValue($_product); // Returns: string(25) "Leverans 3-10 arbetsdagar"
$greenTxt = $_product->getResource()->getAttribute('inventory_green_status_text')->getFrontend()->getValue($_product); // Returns: string(25) "Leverans 3-10 arbetsdagar"

?>

<?php
// Stock qty
$qtyStock = $_product->getExtensionAttributes()->getStockItem()->getQty();

// Date intervall
$TheDate = date('Y-m-d');

$RedExtraStatusStart = $_product->getData('red_xtra_status_start'); // Gets The correct date value.
$RedExtraStatusEnd = $_product->getData('red_xtra_status_end'); // Gets The correct date value.

$RedExtraTxt = $_product->getResource()->getAttribute('red_xtra_status_text')->getFrontend()->getValue($_product); // Attribute: Meddelande om lång leveranstid
// All the above variables returns the correct data, dates and label.

$helper = $this->helper('Crealevant\ProductDeliveryDate\Helper\Data');
?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->getData('notforsale')): ?>
        <?php if ($_product->isAvailable()): ?>
            <?php if ($_product->getTypeId() != 'bundle') : ?>
                <?php if($RedExtraStatusStart == null && $RedExtraStatusEnd == null): ?>
                    <?php // Dont Print out out of stock message ?>
                <?php elseif($TheDate > $RedExtraStatusStart && $TheDate < $RedExtraStatusEnd): ?>
                    <div class="out-of-stock-message">
                        <span><i class="fas fa-truck"></i> <?= $RedExtraTxt ?> </span>
                    </div>
                <?php elseif ($TheDate > $RedExtraStatusStart == false && $TheDate < $RedExtraStatusEnd == false): ?>
                    <div class="out-of-stock-message">
                        <span><i class="fas fa-truck"></i> <?= $RedExtraTxt ?> </span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>