<div class="footer-links box">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_footer_column1')->toHtml();?>
</div>
<div class="footer-links box">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_footer_column2')->toHtml();?>
</div>
<div class="footer-links box">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_footer_payment')->toHtml();?>
</div>