<?php
/**
 * Copyright © 2017 x-mage2(crealevant). All rights reserved.
 * See README.md for details.
 */

use Magento\Framework\App\Action\Action;
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;

// @codingStandardsIgnoreFile
/** @var Crealevant\RelevantTheme\Helper\Data $_themehelper */
$_themehelper = $this->helper('Crealevant\Relevant\Helper\Data');
$theme = $block->getLayout()->createBlock('Crealevant\Relevant\Block\ThemeSettings');

$showQty = \Magento\Framework\App\ObjectManager::getInstance()
    ->get('Magento\Framework\App\Config\ScopeConfigInterface')
    ->getValue('settings/productpage/quantity_field');
$quickview = \Magento\Framework\App\ObjectManager::getInstance()
    ->get('Magento\Framework\App\Config\ScopeConfigInterface')
    ->getValue('settings/categorypage/quickview');

?>
<?php $iterator = 1; ?>
<?php foreach ($items as $_item): ?>
    <?php /* @escapeNotVerified */
    echo ($iterator++ == 1) ? '<div class="product-item-container"><div class="product-item">' : '</div><div class="product-item-container""><div class="product-item">' ?>
    <?php
    $qty = $_themehelper->getStockQty($_item);
    echo '<div class="flag-container">';
    echo $_themehelper->getFlags($_item, 'no');
    echo '</div>';
    ?>
    <?php if ($enableCustomCss == 1): ?>
        <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
    <?php endif; ?>
    <div class="product-item-info">
        <a href="<?php /* @escapeNotVerified */
        echo $_item->getProductUrl() ?>" class="<?php if ($block->getMode() == 'list') {
            echo "col-lg-4 col-md-6 col-sm-6 col-xs-12";
        } ?> product photo product-item-photo <?php if ($theme->getSetting('categorypage', 'quickview') == 1) {
            echo 'crealevant-quickview';
        } ?>" <?php if ($theme->getSetting('categorypage', 'quickview') == 1) {
            echo 'data-cat-url="' . $categoryUrl . '" data-product-url="' . $_product->getProductUrl() . '" data-quickview-url="' . $productUrl . '"';
        } ?>

           href="<?php if ($theme->getSetting('categorypage', 'quickview') == 1) {
               echo 'javascript:void(0);';
           } else {
               echo $_item->getProductUrl();
           } ?>" tabindex="-1">
                                <span style="width:270px;" class="product-image-container">
                         <span style="padding-bottom: 137%;" class="product-image-wrapper">
                        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                        $images = $product->getMediaGalleryImages();
                        $imgCNT = 1;
                        $imgurl2 = "";
                        foreach ($images as $child) {
                            if ($imgCNT == 1) {
                                $imgurl1 = $child->getUrl();
                            } elseif ($imgCNT == 2) {
                                $imgurl2 = $this->helper('Magento\Catalog\Helper\Image')->init($_item, 'product_page_image_large')->keepAspectRatio(true)->keepFrame(true)->setImageFile($child->getFile())->resize(320, 320)->getUrl();
                            } else {
                                break;
                            }
                            $imgCNT++;
                        }
                        $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_item, 'product_page_image_large')->keepAspectRatio(true)->keepFrame(true)->resize(320, 320)->getUrl(); ?>
                             <div class="cf">
                                    <div class="img-overlay"></div>
            <div class="bottomhover <?php echo ($imgurl2) ? "image" : "no- image" ?>">
                <img class="product-image-photo img-responsive" src="<?php echo ($imgurl2) ? $imgurl2 : $imageUrl; ?>">
            </div>
            <div class="tophover <?php echo ($imgurl2) ? "image" : "no-image" ?>">
                <img class="product-image-photo img-responsive" src="<?php echo $imageUrl; ?>">
            </div>
        </div>
    </span>
</span>
        </a>
        <div class="product details product-item-details">

            <strong class="product-item-name">
                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                   href="<?php /* @escapeNotVerified */
                   echo $block->getProductUrl($_item) ?>"
                   class="product-item-link">
                    <?php echo $block->escapeHtml($_item->getName()) ?>
                </a>
            </strong>

            <?php if ($showWishlist || $showCompare || $showCart): ?>
            <div class="product-item-actions">
                <?php if ($showCart): ?>
                <div class="actions-primary">
                    <?php if ($_item->isSaleable()): ?>
                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                    <?php if ($theme->getSetting('general', 'reviewson') == 1) { ?>
                        <?php if ($templateType): ?>
                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                        <?php endif; ?>
                    <?php } ?>

                    <?php if ($showSwatches) : ?>
                        <?php echo $block->getProductDetailsHtml($_item); ?>
                    <?php endif; ?>
                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                    echo $postParams['action']; ?>" method="post">
                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                        echo $postParams['data']['product']; ?>">
                        <input type="hidden" name="<?php /* @escapeNotVerified */
                        echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                        echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                        <?php echo $block->getBlockHtml('formkey') ?>

                        <div class="row">
                            <div class="price-col col-md-12 col-sm-12 col-xs-12">
                                <?php
                                $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                                $store_id = $storeManager->getStore()->getId();
                                $options = $objectManager->get('Magento\Bundle\Model\Option')
                                    ->getResourceCollection()
                                    ->setProductIdFilter($_item->getId())
                                    ->setPositionOrder();
                                $options->joinValues($store_id);
                                $typeInstance = $objectManager->get('Magento\Bundle\Model\Product\Type');
                                $selections = $typeInstance->getSelectionsCollection($typeInstance->getOptionsIds($_item), $_item);
                                $total_price_sum = 0;
                                $total_price_sum_special = 0;
                                $bundle = false;
                                $specialprice = false;
                                $todaysDate =  date("Y-m-d");
                                foreach ($selections as $selection) {
                                    if($selection->getIsDefault() == '1') {
                                        $qty = $selection->getSelectionQty();
                                        $special = $selection->getSpecialPrice();
                                        $FromDate = $selection->getSpecialFromDate();
                                        $ToDate = $selection->getSpecialToDate();
                                        if($special) {
                                            if(($todaysDate > $FromDate) && ($todaysDate < $ToDate)){
                                                $specialprices = $selection->getSpecialPrice() * $qty;
                                                $specialprice = true;
                                                $total_price_sum_special = $total_price_sum_special + $specialprices;
                                            }
                                        }
                                        $prices = $selection->getPrice() * $qty;
                                        $total_price_sum = $total_price_sum + $prices;
                                    }
                                    $bundle = true;

                                }
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
                                $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper

                                if(!$bundle) {
                                    echo $block->getProductPrice($_item);
                                } else {
                                    if($specialprice) {
                                        ?>
                                        <span class="special-price">
                                                        <span class="price">
                                                        <?php
                                                        $formattedPricespec = $priceHelper->currency($total_price_sum_special, true, false);
                                                        echo $formattedPricespec;
                                                        ?>
                                                            </span>
    </span>
                                        <span class="old-price">
                                                                 <span class="price">
                                                        <?php
                                                        $formattedPrice = $priceHelper->currency($total_price_sum, true, false);
                                                        echo $formattedPrice;
                                                        ?>
                                                                 </span>
    </span>
                                        <?php
                                    } else {
                                        $formattedPrice = $priceHelper->currency($total_price_sum, true, false);
                                        echo $formattedPrice;
                                    }
                                }
                                ?>
                            </div>

                            <?php if ($_item->isSaleable() && $showQty == '1'): ?>
                                <div class="qty-col col-md-7 col-sm-6 col-xs-12">
                                    <div class="input-group">
                                  <span class="input-group-btn incdec">
                                      <button type="button" class="btn btn-default btn-number btn-qty"
                                              disabled="disabled"
                                              data-type="minus" data-field="qty<?php /* @escapeNotVerified */
                                      echo $_item->getId() ?>">
                                          <span class="fa fa-minus"></span>
                                      </button>
                                  </span>
                                        <input type="text" id="qty<?php /* @escapeNotVerified */
                                        echo $_item->getId() ?>" name="qty" title="<?php /* @escapeNotVerified */
                                        echo __('Qty') ?>" value="1" class="form-control input-number input-qty incdec"
                                               min="1" max="10000"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                                        <span class="input-group-btn incdec">
                                      <button type="button" class="btn btn-default btn-number btn-qty" data-type="plus"
                                              data-field="qty<?php /* @escapeNotVerified */
                                              echo $_item->getId() ?>">
                                          <span class="fa fa-plus"></span>
                                      </button>
                                  </span>
                                    </div>
                                </div>
                            <?php else: ?>
                            <?php endif; ?>
                            <button type="submit"
                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                    class="action tocart primary btn btn-primary btn-md">
                            <span><i class="rl-cart-add"></i> <div class="text"><?php /* @escapeNotVerified */
                                    echo __('Add to Cart') ?></div></span>
                            </button>
                    </form>
                </div>
            <?php else: ?>
                <?php if ($_item->getIsSalable()): ?>
                    <div class="stock available"><span><?php /* @escapeNotVerified */
                            echo __('In stock') ?></span></div>
                <?php else: ?>
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Out of stock')); ?>"
                            class="action tocart primary btn btn-default btn-md">
                        <span><i class="rl-cart"></i> <div class="text"><?php /* @escapeNotVerified */
                                echo __('Out of stock') ?></div></span>
                    </button>
                <?php endif; ?>
            <?php endif; ?>
            </div>
        <?php endif; ?>
        </div>
        <?php endif; ?>
    </div>
    </div>
    <?php echo ($iterator == count($items) + 1) ? '</div></div>' : '</div>' ?>
<?php endforeach; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Crealevant_ProductSlider/js/slider-settings":{}
        }
    }
</script>
