<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$product = $block->getProduct();
$_order = $_item->getOrder();
$_product = $_item->getProduct();
//Stock
$greenStat = intval($_product->getData('inventory_green_status_min')); // Returns int(0)
$redStat = intval($_product->getData('inventory_red_status_max')); // Returns int(10)
$yellowTxt = $_product->getData('inventory_yellow_status_text');
$redTxt = $_product->getData('inventory_red_status_text');
$greenTxt = $_product->getData('inventory_green_status_text');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$RedExtraStatusStart = $_product->getData('red_xtra_status_start'); // Gets The correct date value.
$RedExtraStatusEnd = $_product->getData('red_xtra_status_end'); // Gets The correct date value.
$TheDate = date('Y-m-d');
$RedExtraTxt = $_product->getResource()->getAttribute('red_xtra_status_text')->getFrontend()->getValue($_product); // Attribute: Meddelande om lång leveranstid
// Stock qty
$qtyStock = $_product->getExtensionAttributes()->getStockItem()->getQty();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($qtyStock >= $greenStat): ?>
            <p class="green-stock"><span><?php echo $greenTxt ?></span></p>
        <?php elseif ($TheDate > $RedExtraStatusStart && $TheDate < $RedExtraStatusEnd): ?>
            <span> <?= $RedExtraTxt ?></span>
        <?php elseif ($qtyStock <= $redStat): ?>
            <p class="red-stock"><span><?php echo $redTxt ?></span></p>
        <?php else: ?>
            <p class="yellow-stock"><span><?php echo $yellowTxt ?></span></p>
        <?php endif; ?>

        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
