<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getOrder() ?>
<?php $_product = $_item->getProduct() ?>

<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildrenItems()); ?>
<?php

//Stock
$greenStat = intval($_product->getData('inventory_green_status_min')); // Returns int(0)
$redStat = intval($_product->getData('inventory_red_status_max')); // Returns int(10)
$yellowTxt = $_product->getData('inventory_yellow_status_text');
$redTxt = $_product->getData('inventory_red_status_text');
$greenTxt = $_product->getData('inventory_green_status_text');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$RedExtraStatusStart = $_product->getData('red_xtra_status_start'); // Gets The correct date value.
$RedExtraStatusEnd = $_product->getData('red_xtra_status_end'); // Gets The correct date value.
$TheDate = date('Y-m-d');
$RedExtraTxt = $_product->getResource()->getAttribute('red_xtra_status_text')->getFrontend()->getValue($_product); // Attribute: Meddelande om lång leveranstid
// Stock qty
$qtyStock = $_product->getExtensionAttributes()->getStockItem()->getQty();
?>
<?php if ($block->getItemOptions() || $_item->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr class="bundle-option-label">
                <td colspan="3">
                    <strong><em><?= /* @escapeNotVerified */  $attributes['option_label'] ?></em></strong>
                </td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!$_item->getParentItem()): ?>
        <tr class="bundle-item bundle-parent">
            <td class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
                <?php if ($qtyStock >= $greenStat): ?>
                    <p class="green-stock"><span><?php echo $greenTxt ?></span></p>
                <?php elseif ($TheDate > $RedExtraStatusStart && $TheDate < $RedExtraStatusEnd): ?>
                    <span> <?= $RedExtraTxt ?></span>
                <?php elseif ($qtyStock <= $redStat): ?>
                    <p class="red-stock"><span><?php echo $redTxt ?></span></p>
                <?php else: ?>
                    <p class="yellow-stock"><span><?php echo $yellowTxt ?></span></p>
                <?php endif; ?>
            </td>
            <td class="item-qty">
                <?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?>
            </td>
            <td class="item-price">
                <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
            </td>
        </tr>
    <?php else: ?>
    <?php
        // Stock For Childrens:
        $childrenGreenStat = intval($_item->getProduct()->getData('inventory_green_status_min')); // Returns int(0)
        $childrenRedStat = intval($_item->getProduct()->getData('inventory_red_status_max')); // Returns int(10)
        $childrenYellowTxt = $_item->getProduct()->getData('inventory_yellow_status_text');
        $childrenRedTxt = $_item->getProduct()->getData('inventory_red_status_text');
        $childrenGreenTxt = $_item->getProduct()->getData('inventory_green_status_text');
        $childrenRedExtraStatusStart = $_item->getProduct()->getData('red_xtra_status_start'); // Gets The correct date value.
        $childrenRedExtraStatusEnd = $_item->getProduct()->getData('red_xtra_status_end'); // Gets The correct date value.
        $childrenRedExtraTxt = $_item->getProduct()->getResource()->getAttribute('red_xtra_status_text')->getFrontend()->getValue($_item->getProduct()); // Attribute: Meddelande om lång leveranstid
        // Children Stock qty
        $childrenQtyStock = $_item->getProduct()->getExtensionAttributes()->getStockItem()->getQty();
        ?>
        <tr class="bundle-item bundle-option-value">
            <td class="item-info" colspan="3">
                <p><?= $block->getValueHtml($_item) ?></p>
                <?php if ($childrenQtyStock >= $childrenGreenStat): ?>
                    <p class="green-stock"><span><?php echo $childrenGreenTxt ?></span></p>
                <?php elseif ($TheDate > $childrenRedExtraStatusStart && $TheDate < $childrenRedExtraStatusEnd): ?>
                    <span> <?= $childrenRedExtraTxt ?></span>
                <?php elseif ($childrenQtyStock <= $childrenRedStat): ?>
                    <p class="red-stock"><span><?php echo $childrenRedTxt ?></span></p>
                <?php else: ?>
                    <p class="yellow-stock"><span><?php echo $childrenYellowTxt ?></span></p>
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>

<?php endforeach; ?>

<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                            <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
            <?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
                <table class="message-gift">
                    <tr>
                        <td>
                            <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                            <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                            <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                        </td>
                    </tr>
                </table>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
